//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomNevaSvyazS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventID { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
        public int RoleID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
